server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: meta
          uri: http://localhost:8083
          predicates:
            - Path=/meta/**
        - id: storage
          uri: http://localhost:8084
          predicates:
            - Path=/storage/**
